### PR TITLE
Update JSDoc

### PR DESCRIPTION
**Pull request by zavr-1**
Hi I've noticed you can make a few changes.

### CODE REVIEW

**Comment by zavr-1** [comment]
I thought you could remove   
```
// remove the parameters	
  type.parameters = undefined
``` 
because the MediaType does not have them ... tests think otherwise...

**Comment by dougwilson** [comment]
Hi @zavr-1 this is because I rewrite the `media-typer` modules to actually correspond to the RFC it references, which has no parameter syntax. I am in the process of making all the necessary changes to this module in order to upgrade it to the newest `media-typer`, but I have not completed the work yet. You can see a preview of the work on the `develop` branch here: https://github.com/jshttp/type-is/tree/develop

**Comment by zavr-1** [comment]
@dougwilson OK thanks so if I do 
```
function normalizeType (value) {
  // parse the type
  var type = contentType.parse(value).type

  if (!typer.test(type)) {
    return null
  }

  return type
}
```
would that be a thorough enough substitute? ty

**Comment by dougwilson** [comment]
I already made the changes on the develop branch. You do not need to make any changes there for your jsdoc fix.

**Comment by zavr-1** [comment]
Yeah I just meant if I wanted to use it, not for the PR. thanks I think you could close this.

**Comment by helio-frota** [comment]
> Yeah I just meant if I wanted to use it, not for the PR. thanks I think you could close this.

Hi,
Closing this pull request as part of triage process.
Thank you.

**Pull request closed without merging**
