### PR TITLE
fix: compatible extra semicolon on content-type header

### PR DESCRIPTION
**Pull request by fengmk2**

### CODE REVIEW

**Comment by fengmk2** [comment]
@dougwilson I think compatible it on `type-is` is better than `koa` level.

**Comment by dougwilson** [comment]
Thanks! I'm not sure the spec allows a semicolon like that, I will need tk check.

**Comment by fengmk2** [comment]
Yes, the standard specification does not contain an extra semicolon inside. This is a feedback from a real application developer, presumably because the http client implementation that calls their service is not sufficiently standardized to cause them to think that this is a problem with the koa application framework.
Instead of fixing it here, I'll see if I can fix it at the koa or eggjs level.

**Comment by dougwilson** [comment]
Ah, gotcha. I mean, I'm not 1000% against the idea, but the issue I always end up with these are just what exactly are the exceptions to the rules? Like in this case it accepts `foo/bar;a=b;;` but then should `foo/bar;;a=b` be ok too?

The question ends up being what exactly are the exceptions to the rules and how far to go until it turns around and becomes some kind of security vulnerability where multiple systems (like firewalls and proxies) and involved where they are interpreting the same request differently?

**Comment by fengmk2** [comment]
I think we just need to fix the values that end with semicolon.
`foo/bar;;a=b` we should not to fixed it.

**Comment by dougwilson** [comment]
Also we'll probably want to have this as a opt-in behavor for non-standards parsing. That usually appeases the sec bug reporters.

**Comment by dougwilson** [comment]
And, really, in this non-strict/quirks mode, it could just chop the string at the first semi instead of doing the work to validate the media type string is valid or not. That would probably be the most flexible and match what a lot of impls who don't validate the media type are doing.

**Pull request closed without merging**
