### PR TITLE
Update code to support media-typer ≥ 1.0.0

### PR DESCRIPTION
**Pull request by guimard**
Hi,

a little patch to be able to use media-typer ≥ 1.0.0

### CODE REVIEW

**Comment by dougwilson** [comment]
I believe this is already covered in the develop branch https://github.com/jshttp/type-is/commits/develop

Is this an alternative solution that should be considered over what is already landed?

**Comment by guimard** [comment]
Sorry, I didn't see this branch. This patch started from master.
Cheers,
Xavier

**Comment by dougwilson** [comment]
Looks like CI does not pass on this PR if you want to look into it. Let me know additionally the answer to my question above :)

**Comment by guimard** [comment]
I don't understand what happens with travis, looks good here...

**Comment by dougwilson** [comment]
I can help look into it, but ideally if I could get the answer for if this is relevant or not first would help know if it's worth fixing.

**Comment by guimard** [comment]
You can close this issue, I'll update Debian package when next release will be out.

Thanks!

**Comment by helio-frota** [comment]
> You can close this issue, I'll update Debian package when next release will be out.

Hi,
Closing this pull request as part of triage process.
Thank you.

**Pull request closed without merging**
